permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:

name: check
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: fmt
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: clippy
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
